trigger:
- main

variables:
  buildConfiguration: 'Release'

stages:
- stage: BuildAndDeploy
  jobs:
  - job: Job
    pool:
      name: 'Default'
      demands:
      - Agent.Name -equals macs-MacBook-Pro
    
    steps:
    # This command works on Mac/Linux to find and build the project
    - script: |
        find . -name "*.csproj" -exec dotnet build {} --configuration $(buildConfiguration) \;
      displayName: 'dotnet build $(buildConfiguration)'