- stage: Deploy
  dependsOn: __default
  jobs:
  - deployment: DeployWeb
    pool:
      name: 'Default'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure subscription 1 (208d95e6-0ef5-401c-a183-3e7c067f8805)'
              appType: 'webApp'
              WebAppName: 'MovieShop'
              packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'