# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
trigger:
- main

variables:
  buildConfiguration: 'Release'

stages:
- stage: BuildAndDeploy
  jobs:
  - job: Job
    pool:
      name: 'Default'
      demands:
      - Agent.Name -equals macs-MacBook-Pro
    
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'